pipeline:
  build:
    group: build
    image: alpine:latest
    commands:
      - apk add curl ripgrep axel openjdk17-jdk
      - sh patch.sh
  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      files:
        - "revanced-*-non-root.apk"
      file-exists: overwrite
      api_key:
        from_secret: CODEBERG_ACCESS_TOKEN
      target: main
      title: apks
      note: "These are revanced-apk's built with this script"
      skip_verify: true
    when:
      event: tag

matrix:
  what_to_patch:
    - youtube
    - youtube-music
    - reddit
    - twitch
    - twitter
    - spotify
    - tiktok
