pipeline:
  build:
    group: build
    image: alpine:latest
    commands:
      - apk add curl ripgrep axel openjdk17-jdk
      - sh patch.sh
    

matrix:
  what_to_patch:
    - youtube
    - youtube-music
    - reddit
    - twitch
    - twitter
    - spotify
    - tiktok
